# pyhub-docs 설정 파일 예제
# 이 파일을 ~/.pyhub/config.yml에 복사하여 사용하세요

# OpenAI API 설정
openai:
  # API 키 (OPENAI_API_KEY 환경 변수로도 설정 가능)
  api_key: "sk-..."
  
  # 기본 모델 (gpt-3.5-turbo, gpt-4)
  model: "gpt-3.5-turbo"
  
  # 최대 토큰 수
  max_tokens: 2000
  
  # 창의성 수준 (0.0-1.0)
  temperature: 0.7

# replace 명령 기본값
replace:
  # 백업 생성 여부
  backup: false
  
  # 하위 디렉토리 포함 여부
  recursive: true
  
  # 실제 변경 없이 미리보기
  dry_run: false
  
  # 제외할 파일 패턴
  exclude: ""
  
  # 동시 처리 활성화
  concurrent: false
  
  # 최대 워커 수 (0 = CPU 코어 수)
  max_workers: 0

# create 명령 기본값
create:
  # 기존 파일 덮어쓰기
  force: false
  
  # 출력 형식 (docx, pptx)
  format: ""

# generate 명령 기본값
generate:
  # 콘텐츠 타입 (blog, report, summary, code, custom)
  content_type: "custom"
  
  # AI 모델
  model: "gpt-3.5-turbo"
  
  # 최대 토큰 수
  max_tokens: 2000
  
  # 창의성 수준
  temperature: 0.7

# template 명령 기본값
template:
  # 기존 파일 덮어쓰기
  force: false

# 전역 설정
global:
  # 상세 출력
  verbose: false
  
  # 조용한 모드 (에러만 출력)
  quiet: false
  
  # 언어 설정 (en, ko)
  lang: "ko"